---

- hosts: all
  become: true
  tasks:

  - name: remove packages from servers and workstations
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ mariadb_package }}"
        - "{{ samba_package }}"
        - "{{ unzip_package }}"
      state: absent
