---

- name: install httpd package (CentOS)
  tags: centos,apache,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd service (CentOS)
  tags: centos,apache,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: install apache2 package (Ubuntu)
  tags: ubuntu,apache,apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
  register: install_apache

- name: start apache2 service (Ubuntu)
  tags: ubuntu,apache,apache2
  ansible.builtin.shell:
    cmd: service apache2 start
  when: install_apache.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change ansible_test.txt file
  tags: apache,apache2,httpd
  lineinfile:
    path: /var/www/html/ansible_test.txt
    regexp: '^name'
    line: root@jmknet.com
  when: ansible_distribution == "Ubuntu"
  register: change_file

- name: restart apache2 (Ubuntu)
  tags: ubuntu,apache,apache2
  ansible.builtin.shell:
    cmd: service apache2 restart
  when: change_file.changed
