---

- name: install mariadb server package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb server package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: "{{ mariadb_package_ubuntu }}"
    state: latest
  when: ansible_distribution == "Ubuntu"
