---

- name: install unzip
  tags: unzip
  package:
    name: "{{ unzip_package }}"

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
